# Generated by Django 5.2 on 2026-03-21 02:22

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField(db_index=True, unique=True)),
                ('fsfsi_score', models.DecimalField(decimal_places=6, max_digits=8)),
                ('stress_level', models.CharField(choices=[('low', 'Low (≤ 0.05)'), ('medium', 'Medium (0.05 - 0.15)'), ('high', 'High (0.15 - 0.30)'), ('critical', 'Critical (> 0.30)')], max_length=20)),
                ('component_scores', models.JSONField(default=dict, help_text='Dict of component -> stress value')),
                ('total_budget_lcu_bn', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('cumulative_fsfsi', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('cumulative_component_scores', models.JSONField(blank=True, default=dict, help_text='Dict of component -> cumulative stress value')),
                ('yoy_change', models.DecimalField(blank=True, decimal_places=6, help_text='Change from previous year', max_digits=8, null=True)),
                ('yoy_change_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Assessment History',
                'verbose_name_plural': 'Assessment History',
                'db_table': 'assessment_history',
                'ordering': ['-fiscal_year'],
            },
        ),
        migrations.CreateModel(
            name='ComponentPersistenceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('markets', 'Markets'), ('crop_production', 'Crop Production'), ('nutrition', 'Nutrition'), ('research', 'Research'), ('post_harvest', 'Post-Harvest'), ('environment', 'Environment'), ('animal_systems', 'Animal Systems'), ('finance', 'Finance')], db_index=True, max_length=30, unique=True)),
                ('rho_up', models.DecimalField(decimal_places=4, default=Decimal('0.40'), help_text='Damage speed (0-1): how fast cumulative stress rises when current stress worsens', max_digits=6)),
                ('rho_down', models.DecimalField(decimal_places=4, default=Decimal('0.15'), help_text='Recovery speed (0-1): how fast cumulative stress falls when current stress improves', max_digits=6)),
            ],
            options={
                'verbose_name': 'Component Persistence Config',
                'db_table': 'component_persistence_config',
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField(db_index=True)),
                ('assessment_name', models.CharField(blank=True, default='', help_text='Optional name for this assessment', max_length=255)),
                ('weighting_method', models.CharField(choices=[('expert', 'Expert (AHP)'), ('financial', 'Financial (Budget-based)'), ('network', 'Network (PageRank)'), ('hybrid', 'Hybrid (Default)')], default='hybrid', max_length=20)),
                ('scenario', models.CharField(choices=[('normal_operations', 'Normal Operations'), ('climate_shock', 'Climate Shock'), ('financial_crisis', 'Financial Crisis'), ('pandemic_disruption', 'Pandemic Disruption'), ('supply_chain_disruption', 'Supply Chain Disruption')], default='normal_operations', max_length=30)),
                ('fsfsi_score', models.DecimalField(decimal_places=6, help_text='System-level FSFSI: Σᵢ ωᵢ · δᵢ · e^(-αᵢfᵢ)', max_digits=8)),
                ('stress_level', models.CharField(choices=[('low', 'Low (≤ 0.05)'), ('medium', 'Medium (0.05 - 0.15)'), ('high', 'High (0.15 - 0.30)'), ('critical', 'Critical (> 0.30)')], max_length=20)),
                ('fsfsi_optimal', models.DecimalField(blank=True, decimal_places=6, help_text='FSFSI under optimal allocation', max_digits=8, null=True)),
                ('efficiency_index', models.DecimalField(blank=True, decimal_places=6, help_text='FSFSI_optimal / FSFSI_actual (closer to 1 = better)', max_digits=8, null=True)),
                ('gap_ratio', models.DecimalField(blank=True, decimal_places=6, help_text='(FSFSI_actual - FSFSI_optimal) / FSFSI_optimal', max_digits=10, null=True)),
                ('cumulative_fsfsi', models.DecimalField(blank=True, decimal_places=6, help_text='System cumulative FSFSI: Σ ωᵢ · CS_i(t)', max_digits=8, null=True)),
                ('cumulative_stress_level', models.CharField(blank=True, choices=[('low', 'Low (≤ 0.05)'), ('medium', 'Medium (0.05 - 0.15)'), ('high', 'High (0.15 - 0.30)'), ('critical', 'Critical (> 0.30)')], help_text='Stress classification based on cumulative FSFSI', max_length=20, null=True)),
                ('total_budget_lcu_bn', models.DecimalField(blank=True, decimal_places=4, help_text='Total budget in billions LCU', max_digits=15, null=True)),
                ('total_budget_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Total budget in USD', max_digits=18, null=True)),
                ('indicators_count', models.IntegerField(default=0)),
                ('components_count', models.IntegerField(default=0)),
                ('result_json', models.JSONField(default=dict, help_text='Complete assessment output including component details')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('computing_time_ms', models.IntegerField(blank=True, null=True)),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment Result',
                'verbose_name_plural': 'Assessment Results',
                'db_table': 'assessment_results',
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component', models.CharField(choices=[('markets', 'Markets'), ('crop_production', 'Crop Production'), ('nutrition', 'Nutrition'), ('research', 'Research'), ('post_harvest', 'Post-Harvest'), ('environment', 'Environment'), ('animal_systems', 'Animal Systems'), ('finance', 'Finance')], db_index=True, max_length=30)),
                ('weight', models.DecimalField(decimal_places=6, help_text='Component weight ωᵢ', max_digits=8)),
                ('avg_performance_gap', models.DecimalField(decimal_places=6, help_text='Average performance gap across indicators', max_digits=8)),
                ('component_stress', models.DecimalField(decimal_places=6, help_text='Component stress value', max_digits=8)),
                ('weighted_stress', models.DecimalField(decimal_places=6, help_text='ωᵢ · υᵢ contribution to system FSFSI', max_digits=8)),
                ('priority_level', models.CharField(choices=[('low', 'Low (≤ 0.05)'), ('medium', 'Medium (0.05 - 0.15)'), ('high', 'High (0.15 - 0.30)'), ('critical', 'Critical (> 0.30)')], help_text='Priority level for this component', max_length=20)),
                ('cumulative_stress', models.DecimalField(blank=True, decimal_places=6, help_text='Cumulative stress CS_i(t): accounts for damage persistence and slow recovery', max_digits=8, null=True)),
                ('cumulative_weighted_stress', models.DecimalField(blank=True, decimal_places=6, help_text='ωᵢ · CS_i(t) contribution to system cumulative FSFSI', max_digits=8, null=True)),
                ('budget_lcu_bn', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('budget_share_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('optimal_allocation_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Recommended allocation from optimization', max_digits=18, null=True)),
                ('allocation_gap_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Difference between optimal and current', max_digits=18, null=True)),
                ('indicators_count', models.IntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_results', to='assessments.assessmentresult')),
            ],
            options={
                'verbose_name': 'Component Result',
                'verbose_name_plural': 'Component Results',
                'db_table': 'component_results',
                'ordering': ['assessment', '-weighted_stress'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indicator_code', models.CharField(db_index=True, max_length=20)),
                ('indicator_name', models.CharField(max_length=255)),
                ('component', models.CharField(choices=[('markets', 'Markets'), ('crop_production', 'Crop Production'), ('nutrition', 'Nutrition'), ('research', 'Research'), ('post_harvest', 'Post-Harvest'), ('environment', 'Environment'), ('animal_systems', 'Animal Systems'), ('finance', 'Finance')], max_length=30)),
                ('observed_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('benchmark_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('financial_allocation', models.DecimalField(blank=True, decimal_places=4, help_text='In millions USD', max_digits=15, null=True)),
                ('sensitivity', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('performance_gap', models.DecimalField(decimal_places=6, help_text='δᵢ = |xᵢ - x̄ᵢ| / max(xᵢ, x̄ᵢ)', max_digits=8)),
                ('stress_value', models.DecimalField(decimal_places=6, help_text='υᵢ(fᵢ) = δᵢ · e^(-αᵢfᵢ)', max_digits=8)),
                ('cumulative_stress', models.DecimalField(blank=True, decimal_places=6, help_text='Cumulative indicator stress: accounts for damage persistence', max_digits=8, null=True)),
                ('weighted_lcu_bn', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('share_weighted_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_results', to='assessments.assessmentresult')),
            ],
            options={
                'verbose_name': 'Indicator Result',
                'verbose_name_plural': 'Indicator Results',
                'db_table': 'indicator_results',
                'ordering': ['assessment', 'component', 'indicator_code'],
            },
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['fiscal_year', 'weighting_method'], name='assessment__fiscal__fcc029_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['computed_at'], name='assessment__compute_051a4f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='componentresult',
            unique_together={('assessment', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='indicatorresult',
            unique_together={('assessment', 'indicator_code')},
        ),
    ]
