# Generated by Django 5.2 on 2026-03-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresult',
            name='weighting_method',
            field=models.CharField(choices=[('equal', 'Equal (1/n indicators)'), ('expert', 'Expert (AHP)'), ('financial', 'Financial (Budget-based)'), ('network', 'Network (PageRank)'), ('hybrid', 'Hybrid (Default)')], default='hybrid', max_length=20),
        ),
    ]
