# Generated by Django 5.1.6 on 2026-03-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial_assessment_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenthistory',
            name='stress_level',
            field=models.CharField(choices=[('low', 'Low (≤ 0.05)'), ('medium', 'Medium (0.05 - 0.15)'), ('high', 'High (0.15 - 0.30)'), ('critical', 'Critical (> 0.30)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='stress_level',
            field=models.CharField(choices=[('low', 'Low (≤ 0.05)'), ('medium', 'Medium (0.05 - 0.15)'), ('high', 'High (0.15 - 0.30)'), ('critical', 'Critical (> 0.30)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='componentresult',
            name='priority_level',
            field=models.CharField(choices=[('low', 'Low (≤ 0.05)'), ('medium', 'Medium (0.05 - 0.15)'), ('high', 'High (0.15 - 0.30)'), ('critical', 'Critical (> 0.30)')], help_text='Priority level for this component', max_length=20),
        ),
    ]
