# Generated by Django 5.2.12 on 2026-03-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_align_stress_thresholds_with_rust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenthistory',
            name='yoy_change_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
