# Generated by Django 5.2.12 on 2026-10-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_uniq_plan_name_per_fy'),
    ]

    operations = [
        migrations.CreateModel(
            name='StressThresholdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('indicator', 'Indicator stress'), ('component', 'Component stress'), ('system', 'System FSFSI'), ('coverage', 'Financing coverage')], max_length=20, unique=True)),
                ('low_max', models.DecimalField(decimal_places=6, help_text="Upper bound of 'low'", max_digits=8)),
                ('medium_max', models.DecimalField(decimal_places=6, help_text="Upper bound of 'medium'", max_digits=8)),
                ('high_max', models.DecimalField(blank=True, decimal_places=6, help_text="Upper bound of 'high' (above → 'critical'); NULL for 3-class levels", max_digits=8, null=True)),
                ('method', models.CharField(default='jenks_natural_breaks', help_text='jenks_natural_breaks | inherited_component_scale | engine_default | manual', max_length=40)),
                ('n_observations', models.IntegerField(default=0)),
                ('gvf', models.DecimalField(blank=True, decimal_places=6, help_text='Goodness-of-variance fit of the Jenks partition (0–1)', max_digits=8, null=True)),
                ('calibration_years', models.JSONField(blank=True, default=list)),
                ('calibrated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Stress Threshold Config',
                'db_table': 'stress_threshold_config',
                'ordering': ['level'],
            },
        ),
        migrations.AddField(
            model_name='componentresult',
            name='cumulative_priority_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Classification of cumulative_stress (component-level calibrated thresholds)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='componentresult',
            name='diagnosis',
            field=models.CharField(blank=True, choices=[('at_benchmark', 'At / near benchmark'), ('unfunded_gap', 'Gap, largely unfunded'), ('partially_funded_gap', 'Gap, partially funded'), ('funded_gap', 'Gap funded; outcome lag')], help_text='Gap × financing-coverage diagnosis', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='componentresult',
            name='financing_coverage',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='1 − stress/gap = share of the performance gap absorbed by financing (0–1)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='diagnosis',
            field=models.CharField(blank=True, choices=[('at_benchmark', 'At / near benchmark'), ('unfunded_gap', 'Gap, largely unfunded'), ('partially_funded_gap', 'Gap, partially funded'), ('funded_gap', 'Gap funded; outcome lag')], help_text='Gap × financing-coverage diagnosis', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='financing_coverage',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='1 − υ/δ = 1 − e^(−αf): share of the gap absorbed by financing (0–1)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='stress_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Classification of stress_value (indicator-level calibrated thresholds)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmenthistory',
            name='stress_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='cumulative_stress_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Stress classification based on cumulative FSFSI', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='stress_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='componentresult',
            name='priority_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Classification of component_stress (component-level calibrated thresholds)', max_length=20),
        ),
    ]
