# Generated by Django 5.2.12 on 2026-03-20 18:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_widen_yoy_change_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentPersistenceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('markets', 'Markets'), ('crop_production', 'Crop Production'), ('nutrition', 'Nutrition'), ('research', 'Research'), ('post_harvest', 'Post-Harvest'), ('environment', 'Environment'), ('animal_systems', 'Animal Systems'), ('finance', 'Finance')], db_index=True, max_length=30, unique=True)),
                ('rho_up', models.DecimalField(decimal_places=4, default=Decimal('0.40'), help_text='Damage speed (0-1): how fast cumulative stress rises when current stress worsens', max_digits=6)),
                ('rho_down', models.DecimalField(decimal_places=4, default=Decimal('0.15'), help_text='Recovery speed (0-1): how fast cumulative stress falls when current stress improves', max_digits=6)),
            ],
            options={
                'verbose_name': 'Component Persistence Config',
                'db_table': 'component_persistence_config',
            },
        ),
        migrations.AddField(
            model_name='assessmenthistory',
            name='cumulative_component_scores',
            field=models.JSONField(blank=True, default=dict, help_text='Dict of component -> cumulative stress value'),
        ),
        migrations.AddField(
            model_name='assessmenthistory',
            name='cumulative_fsfsi',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='cumulative_fsfsi',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='System cumulative FSFSI: Σ ωᵢ · CS_i(t)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='cumulative_stress_level',
            field=models.CharField(blank=True, choices=[('low', 'Low (≤ 0.05)'), ('medium', 'Medium (0.05 - 0.15)'), ('high', 'High (0.15 - 0.30)'), ('critical', 'Critical (> 0.30)')], help_text='Stress classification based on cumulative FSFSI', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='componentresult',
            name='cumulative_stress',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Cumulative stress CS_i(t): accounts for damage persistence and slow recovery', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='componentresult',
            name='cumulative_weighted_stress',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='ωᵢ · CS_i(t) contribution to system cumulative FSFSI', max_digits=8, null=True),
        ),
    ]
