# Generated by Django 5.2.12 on 2026-03-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_cumulative_stress'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorresult',
            name='cumulative_stress',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Cumulative indicator stress: accounts for damage persistence', max_digits=8, null=True),
        ),
    ]
