# Generated by Django 5.2.12 on 2026-10-08 00:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GapAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField()),
                ('analysis_type', models.CharField(choices=[('gaps', 'Gap Analysis'), ('peers', 'Peer Comparison'), ('targets', 'Target Recommendations')], max_length=50)),
                ('average_gap', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('worst_gap_component', models.CharField(blank=True, max_length=50)),
                ('best_gap_component', models.CharField(blank=True, max_length=50)),
                ('on_track_count', models.IntegerField(default=0)),
                ('behind_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('rwanda_rank', models.IntegerField(blank=True, null=True)),
                ('total_peers', models.IntegerField(blank=True, null=True)),
                ('target_year', models.IntegerField(blank=True, null=True)),
                ('years_to_target', models.IntegerField(blank=True, null=True)),
                ('result_json', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('computing_time_ms', models.IntegerField(default=0)),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gap_analysis_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('markets', 'Markets'), ('crop_production', 'Crop Production'), ('nutrition', 'Nutrition'), ('research', 'Research'), ('post_harvest', 'Post-Harvest'), ('environment', 'Environment'), ('animal_systems', 'Animal Systems'), ('finance', 'Finance')], max_length=50)),
                ('observed_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('benchmark_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('gap', models.DecimalField(decimal_places=4, max_digits=8)),
                ('gap_pct', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stress', models.DecimalField(decimal_places=4, max_digits=8)),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('behind', 'Behind'), ('critical', 'Critical')], max_length=20)),
                ('rank', models.IntegerField(default=0)),
                ('recommendation', models.TextField(blank=True)),
                ('recommended_target', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('target_gap', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('annual_improvement_needed', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('priority', models.CharField(blank=True, max_length=20)),
                ('gap_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_gaps', to='optimization.gapanalysisresult')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField()),
                ('analysis_type', models.CharField(choices=[('efficiency', 'Efficiency Analysis'), ('reallocation', 'Reallocation Plan'), ('roi', 'ROI Analysis')], max_length=50)),
                ('total_budget_lcu_bn', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('total_budget_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('current_fsfsi', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('optimal_fsfsi', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('efficiency_index', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('improvement_potential', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('result_json', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('computing_time_ms', models.IntegerField(default=0)),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimization_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('markets', 'Markets'), ('crop_production', 'Crop Production'), ('nutrition', 'Nutrition'), ('research', 'Research'), ('post_harvest', 'Post-Harvest'), ('environment', 'Environment'), ('animal_systems', 'Animal Systems'), ('finance', 'Finance')], max_length=50)),
                ('current_allocation_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('optimal_allocation_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('allocation_gap_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('allocation_gap_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('current_stress', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('optimal_stress', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('stress_reduction', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('roi_per_million', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('roi_rank', models.IntegerField(blank=True, null=True)),
                ('is_underfunded', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('recommendation', models.TextField(blank=True)),
                ('optimization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_optimizations', to='optimization.optimizationresult')),
            ],
            options={
                'ordering': ['priority', 'component'],
            },
        ),
        migrations.AddIndex(
            model_name='gapanalysisresult',
            index=models.Index(fields=['fiscal_year', 'analysis_type'], name='optimizatio_fiscal__c66709_idx'),
        ),
        migrations.AddIndex(
            model_name='gapanalysisresult',
            index=models.Index(fields=['computed_at'], name='optimizatio_compute_90c288_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='componentgap',
            unique_together={('gap_analysis', 'component')},
        ),
        migrations.AddIndex(
            model_name='optimizationresult',
            index=models.Index(fields=['fiscal_year', 'analysis_type'], name='optimizatio_fiscal__05a1f4_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationresult',
            index=models.Index(fields=['computed_at'], name='optimizatio_compute_712c95_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='componentoptimization',
            unique_together={('optimization', 'component')},
        ),
    ]
