# Generated by Django 5.2.12 on 2026-03-10 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField(unique=True)),
                ('lcu_per_usd', models.DecimalField(decimal_places=4, help_text='Local Currency Units per 1 USD', max_digits=15)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exchange_rates',
                'ordering': ['-fiscal_year'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='e.g., IND-01, IND-16', max_length=20, unique=True)),
                ('name', models.CharField(help_text='e.g., Yield (t/ha)', max_length=255)),
                ('component', models.CharField(choices=[('markets', 'Markets'), ('crop_production', 'Crop Production'), ('nutrition', 'Nutrition'), ('research', 'Research'), ('post_harvest', 'Post-Harvest'), ('environment', 'Environment'), ('animal_systems', 'Animal Systems'), ('finance', 'Finance')], db_index=True, help_text='Parent indicator component', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(blank=True, default='', help_text='e.g., %, t/ha, USD', max_length=50)),
                ('higher_is_better', models.BooleanField(default=True, help_text='True if higher values are better (e.g., yield). False for metrics like stunting rate.')),
                ('default_sensitivity', models.DecimalField(decimal_places=6, default=0.001, help_text='Default αᵢ for FSFSI calculation', max_digits=10)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicators',
                'db_table': 'indicators',
                'ordering': ['component', 'display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLineMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField(db_index=True, help_text='e.g., 2018 from 2018/2019')),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('mda', models.CharField(blank=True, default='', max_length=255)),
                ('sub_program_name', models.CharField(blank=True, default='', max_length=255)),
                ('project_name', models.CharField(blank=True, default='', max_length=500)),
                ('budget_line', models.CharField(blank=True, default='', max_length=500)),
                ('type', models.CharField(blank=True, default='', max_length=50)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('specific_supportive', models.CharField(blank=True, default='', max_length=100)),
                ('group', models.CharField(blank=True, default='', max_length=100)),
                ('food_system_component', models.CharField(blank=True, default='', max_length=100)),
                ('amount_gross_lcu', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_weighted_lcu', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('primary_indicator', models.CharField(blank=True, default='', max_length=100)),
                ('direct_effect_pathway', models.TextField(blank=True, default='')),
                ('key_references', models.TextField(blank=True, default='')),
                ('match_type', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('indicator_component', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('indicator', models.CharField(blank=True, default='', max_length=255)),
                ('specification', models.TextField(blank=True, default='')),
                ('benchmark', models.CharField(blank=True, default='', max_length=100)),
                ('gap', models.CharField(blank=True, default='', max_length=100)),
                ('responsiveness', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Budget Line Mapping',
                'verbose_name_plural': 'Budget Line Mappings',
                'db_table': 'budget_line_mappings',
                'ordering': ['fiscal_year', 'indicator_component', 'primary_indicator'],
                'indexes': [models.Index(fields=['fiscal_year', 'indicator_component'], name='budget_line_fiscal__7ccabb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComponentAggregation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component', models.CharField(choices=[('markets', 'Markets'), ('crop_production', 'Crop Production'), ('nutrition', 'Nutrition'), ('research', 'Research'), ('post_harvest', 'Post-Harvest'), ('environment', 'Environment'), ('animal_systems', 'Animal Systems'), ('finance', 'Finance')], db_index=True, max_length=30)),
                ('fiscal_year', models.IntegerField(db_index=True)),
                ('total_records', models.IntegerField(default=0)),
                ('total_gross_lcu_bn', models.DecimalField(decimal_places=4, max_digits=15)),
                ('total_weighted_lcu_bn', models.DecimalField(decimal_places=4, max_digits=15)),
                ('share_of_total_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('avg_performance_gap', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('component_stress', models.DecimalField(blank=True, decimal_places=6, help_text='Aggregated stress for this component', max_digits=8, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=4, help_text='Component importance weight ωᵢ', max_digits=6, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Component Aggregation',
                'verbose_name_plural': 'Component Aggregations',
                'db_table': 'component_aggregations',
                'ordering': ['-fiscal_year', 'component'],
                'unique_together': {('component', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='IndicatorData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField(db_index=True, help_text='e.g., 2025 for FY 2025/2026')),
                ('records_count', models.IntegerField(default=0, help_text='Number of budget line records for this indicator')),
                ('fallback_records', models.IntegerField(default=0, help_text='Number of fallback/estimated records')),
                ('gross_lcu_bn', models.DecimalField(decimal_places=4, help_text='Gross budget in Local Currency Units (billions)', max_digits=15)),
                ('weighted_lcu_bn', models.DecimalField(decimal_places=4, help_text='Weighted budget in LCU (billions)', max_digits=15)),
                ('share_weighted_percent', models.DecimalField(decimal_places=4, help_text='Share of total weighted budget (%)', max_digits=8)),
                ('observed_value', models.DecimalField(blank=True, decimal_places=4, help_text='Current performance metric value', max_digits=15, null=True)),
                ('benchmark_value', models.DecimalField(blank=True, decimal_places=4, help_text='Target/benchmark value', max_digits=15, null=True)),
                ('financial_allocation_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Budget allocation in USD', max_digits=18, null=True)),
                ('sensitivity_parameter', models.DecimalField(blank=True, decimal_places=6, help_text='Override αᵢ for this specific record', max_digits=10, null=True)),
                ('performance_gap', models.DecimalField(blank=True, decimal_places=6, help_text='Computed δᵢ', max_digits=8, null=True)),
                ('stress_value', models.DecimalField(blank=True, decimal_places=6, help_text='Computed υᵢ(fᵢ) = δᵢ · e^(-αᵢfᵢ)', max_digits=8, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_indicator_data', to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_records', to='fsfvi_data.indicator')),
            ],
            options={
                'verbose_name': 'Indicator Data',
                'verbose_name_plural': 'Indicator Data',
                'db_table': 'indicator_data',
                'ordering': ['-fiscal_year', 'indicator__component', 'indicator__code'],
                'indexes': [models.Index(fields=['fiscal_year', 'status'], name='indicator_d_fiscal__8a9e04_idx'), models.Index(fields=['indicator', 'fiscal_year'], name='indicator_d_indicat_98f982_idx')],
                'unique_together': {('indicator', 'fiscal_year')},
            },
        ),
    ]
