# Generated by Django 5.2.12 on 2026-03-20 22:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0005_indicator_cumulative_stress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedStrategicPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField(db_index=True)),
                ('plan_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('planning_years', models.IntegerField()),
                ('target_fsfvi', models.DecimalField(decimal_places=6, max_digits=8)),
                ('target_reduction_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yearly_budget_growth_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('target_curve', models.CharField(default='smoothstep', max_length=20)),
                ('baseline_fsfsi', models.DecimalField(decimal_places=6, max_digits=8)),
                ('final_projected_fsfsi', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('total_additional_investment', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('plan_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_plans', to='assessments.assessmentresult')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_strategic_plans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fiscal_year', 'is_active'], name='saved_strat_fiscal__f2199d_idx')],
            },
        ),
    ]
