# Generated by Django 5.2 on 2026-03-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedstrategicplan',
            name='scenario',
            field=models.CharField(default='normal_operations', max_length=64),
        ),
        migrations.AddField(
            model_name='savedstrategicplan',
            name='weighting_method',
            field=models.CharField(db_index=True, default='hybrid', max_length=32),
        ),
    ]
