# Generated by Django 5.2 on 2026-03-21 02:50

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def backfill_empty_plan_names(apps, schema_editor):
    SavedStrategicPlan = apps.get_model("planning", "SavedStrategicPlan")
    for p in SavedStrategicPlan.objects.filter(plan_name=""):
        p.plan_name = f"Plan {str(p.pk)[:8]}"
        p.save(update_fields=["plan_name"])


def dedupe_plan_names(apps, schema_editor):
    SavedStrategicPlan = apps.get_model("planning", "SavedStrategicPlan")
    from collections import defaultdict

    groups = defaultdict(list)
    for p in SavedStrategicPlan.objects.all().order_by("created_at", "pk"):
        key = (p.fiscal_year, (p.plan_name or "").strip().lower())
        groups[key].append(p)

    for _key, rows in groups.items():
        if len(rows) <= 1:
            continue
        base = rows[0].plan_name.strip()
        used = {base.lower()}
        for p in rows[1:]:
            n = 2
            while True:
                candidate = f"{base} ({n})"
                if candidate.strip().lower() not in used:
                    p.plan_name = candidate
                    used.add(candidate.strip().lower())
                    p.save(update_fields=["plan_name"])
                    break
                n += 1


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0002_saved_plan_weighting_scenario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(backfill_empty_plan_names, noop_reverse),
        migrations.RunPython(dedupe_plan_names, noop_reverse),
        migrations.AddConstraint(
            model_name="savedstrategicplan",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("plan_name"),
                models.F("fiscal_year"),
                name="uniq_saved_plan_name_per_fy_ci",
            ),
        ),
    ]
