# Generated by Django 5.1.6 on 2026-03-21 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_uniq_plan_name_per_fy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanYearActual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_year', models.IntegerField()),
                ('fiscal_year', models.IntegerField(db_index=True)),
                ('total_budget_bn', models.DecimalField(decimal_places=4, max_digits=14)),
                ('component_allocations_bn', models.JSONField(default=dict)),
                ('simulated_cumulative_fsfsi', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('simulated_component_stress', models.JSONField(blank=True, default=dict)),
                ('delta_vs_plan_fsfsi', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_actuals', to='planning.savedstrategicplan')),
            ],
            options={
                'db_table': 'plan_year_actuals',
                'ordering': ['plan_year'],
                'constraints': [models.UniqueConstraint(models.F('plan'), models.F('plan_year'), name='uniq_plan_year_actual')],
            },
        ),
    ]
