# Generated by Django 5.1.6 on 2026-03-21 14:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_add_plan_year_actual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PSTA5Pillar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_fr', models.CharField(blank=True, max_length=255)),
                ('name_rw', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=4, default=Decimal('0.2000'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'PSTA-5 Pillar',
                'verbose_name_plural': 'PSTA-5 Pillars',
                'db_table': 'psta5_pillars',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PSTA5KPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('name_fr', models.CharField(blank=True, max_length=255)),
                ('name_rw', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('baseline_year', models.IntegerField(default=2023)),
                ('baseline_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('target_year', models.IntegerField(default=2029)),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('higher_is_better', models.BooleanField(default=True)),
                ('weight', models.DecimalField(decimal_places=4, default=Decimal('0.2500'), max_digits=5)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='planning.psta5pillar')),
            ],
            options={
                'verbose_name': 'PSTA-5 KPI',
                'verbose_name_plural': 'PSTA-5 KPIs',
                'db_table': 'psta5_kpis',
                'ordering': ['pillar__sort_order', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PSTA5ComponentMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component', models.CharField(max_length=50)),
                ('contribution_weight', models.DecimalField(decimal_places=4, max_digits=5)),
                ('indicator_codes', models.JSONField(blank=True, default=list)),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_mappings', to='planning.psta5pillar')),
            ],
            options={
                'db_table': 'psta5_component_mappings',
                'ordering': ['pillar__sort_order', 'component'],
            },
        ),
        migrations.CreateModel(
            name='PSTA5Progress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField()),
                ('actual_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='planning.psta5kpi')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psta5_progress',
                'ordering': ['kpi', '-fiscal_year'],
            },
        ),
        migrations.CreateModel(
            name='PSTA5AnnualTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField()),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_targets', to='planning.psta5kpi')),
            ],
            options={
                'db_table': 'psta5_annual_targets',
                'ordering': ['kpi', 'fiscal_year'],
                'constraints': [models.UniqueConstraint(models.F('kpi'), models.F('fiscal_year'), name='uniq_kpi_annual_target')],
            },
        ),
        migrations.AddConstraint(
            model_name='psta5kpi',
            constraint=models.UniqueConstraint(models.F('pillar'), models.F('code'), name='uniq_kpi_code_per_pillar'),
        ),
        migrations.AddConstraint(
            model_name='psta5componentmapping',
            constraint=models.UniqueConstraint(models.F('pillar'), models.F('component'), name='uniq_pillar_component'),
        ),
        migrations.AddConstraint(
            model_name='psta5progress',
            constraint=models.UniqueConstraint(models.F('kpi'), models.F('fiscal_year'), name='uniq_kpi_progress_per_year'),
        ),
    ]
