# Generated by Django 5.2.12 on 2026-04-04 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_psta5_kpi_component_mapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psta5kpicomponentmapping',
            options={'ordering': ['kpi__pillar__sort_order', 'kpi__sort_order', '-weight']},
        ),
    ]
