# Generated by Django 4.2.21 on 2025-06-07 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("component_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("component_name", models.CharField(max_length=100)),
                ("component_type", models.CharField(max_length=50)),
                ("observed_value", models.FloatField()),
                ("benchmark_value", models.FloatField()),
                ("financial_allocation", models.FloatField()),
                ("weight", models.FloatField()),
                ("sensitivity_parameter", models.FloatField()),
                ("performance_gap", models.FloatField(null=True)),
                ("vulnerability", models.FloatField(null=True)),
                ("weighted_vulnerability", models.FloatField(null=True)),
                ("efficiency_index", models.FloatField(null=True)),
                ("priority_level", models.CharField(max_length=20, null=True)),
            ],
            options={
                "ordering": ["component_type", "component_name"],
            },
        ),
        migrations.CreateModel(
            name="FSFVISession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("country_name", models.CharField(max_length=100)),
                ("fiscal_year", models.IntegerField()),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("budget_unit", models.CharField(default="millions", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="active", max_length=20)),
                ("total_budget", models.FloatField()),
                ("method_used", models.CharField(default="hybrid", max_length=50)),
                (
                    "scenario",
                    models.CharField(default="normal_operations", max_length=50),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeightAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_weight", models.FloatField()),
                ("adjusted_weight", models.FloatField()),
                ("adjustment_reason", models.TextField(null=True)),
                ("priority_setting", models.CharField(max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fsfvi.component",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_adjustments",
                        to="fsfvi.fsfvisession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("error", "Error"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("processing_log", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("total_records", models.IntegerField(blank=True, null=True)),
                ("component_types_found", models.JSONField(blank=True, null=True)),
                ("data_quality_score", models.FloatField(blank=True, null=True)),
                (
                    "session",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_file",
                        to="fsfvi.fsfvisession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fsfvi_value", models.FloatField()),
                ("total_allocation", models.FloatField()),
                ("average_vulnerability", models.FloatField()),
                ("max_vulnerability", models.FloatField()),
                ("risk_level", models.CharField(max_length=20)),
                ("priority_counts", models.JSONField()),
                ("allocation_concentration", models.FloatField(null=True)),
                ("vulnerability_concentration", models.FloatField(null=True)),
                ("diversification_index", models.FloatField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_analysis",
                        to="fsfvi.fsfvisession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScenarioAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenario_name", models.CharField(max_length=50)),
                ("shock_magnitude", models.FloatField()),
                ("baseline_fsfvi", models.FloatField()),
                ("scenario_fsfvi", models.FloatField()),
                ("impact_analysis", models.JSONField()),
                ("recovery_analysis", models.JSONField(null=True)),
                ("resilience_assessment", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="fsfvi.fsfvisession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_type", models.CharField(max_length=50)),
                ("report_data", models.JSONField()),
                ("executive_summary", models.TextField(null=True)),
                ("technical_details", models.JSONField(null=True)),
                ("visualizations", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="fsfvi.fsfvisession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OptimizationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_fsfvi", models.FloatField()),
                ("optimized_fsfvi", models.FloatField()),
                ("improvement_potential", models.FloatField()),
                ("reallocation_intensity", models.FloatField()),
                ("optimization_method", models.CharField(max_length=50)),
                ("constraints", models.JSONField(null=True)),
                ("absolute_gap", models.FloatField()),
                ("gap_ratio", models.FloatField()),
                ("efficiency_index", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimization",
                        to="fsfvi.fsfvisession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComponentOptimization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_allocation", models.FloatField()),
                ("optimized_allocation", models.FloatField()),
                ("allocation_change", models.FloatField()),
                ("allocation_change_percent", models.FloatField()),
                (
                    "implementation_complexity",
                    models.CharField(max_length=20, null=True),
                ),
                ("reallocation_priority", models.CharField(max_length=20, null=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fsfvi.component",
                    ),
                ),
                (
                    "optimization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_optimizations",
                        to="fsfvi.optimizationresult",
                    ),
                ),
            ],
            options={
                "ordering": ["-allocation_change_percent"],
            },
        ),
        migrations.AddField(
            model_name="component",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="fsfvi.fsfvisession",
            ),
        ),
    ]
